version: '3.8'

services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=1

  celery_worker:
    command: watchmedo auto-restart --directory=./app --pattern=*.py --recursive -- celery -A app.tasks.worker worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=1